"""The CCSDS OEM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`OemFile` the KVN reader produces and serialises
back out through orbit-formats' own MIT xsdata bindings. The committed
``golden_roundtrip.xml`` is the XML twin of ``golden_roundtrip.oem`` — generated by the XML
writer from the KVN golden — so the two goldens carry identical orbital content and the
parity assertion is a true reference (KVN) vs candidate (XML) comparison.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import numpy as np
import pytest

from orbit_formats import (
    Ephemeris,
    MalformedSourceError,
    Metadata,
    Provenance,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.oem_xml import oemfile_from_xml
from orbit_formats.readers.ccsds import OemFile
from orbit_formats.writers.oem import write_oem

DATA = Path(__file__).parent / "data" / "oem"
GOLDEN_KVN = DATA / "golden_roundtrip.oem"
GOLDEN_XML = DATA / "golden_roundtrip.xml"
SAMPLE_XML = DATA / "sample_oem.xml"

# A single-segment OEM in XML, position/velocity only — the minimal reader fixture.
OEM_XML_MIN = b"""<?xml version="1.0" encoding="UTF-8"?>
<oem id="CCSDS_OEM_VERS" version="3.0">
  <header>
    <COMMENT>a test OEM</COMMENT>
    <CREATION_DATE>2002-11-04T17:22:31</CREATION_DATE>
    <ORIGINATOR>NASA/JPL</ORIGINATOR>
  </header>
  <body>
    <segment>
      <metadata>
        <OBJECT_NAME>MARS GLOBAL SURVEYOR</OBJECT_NAME>
        <OBJECT_ID>1996-062A</OBJECT_ID>
        <CENTER_NAME>MARS BARYCENTER</CENTER_NAME>
        <REF_FRAME>EME2000</REF_FRAME>
        <TIME_SYSTEM>UTC</TIME_SYSTEM>
        <START_TIME>1996-12-18T12:00:00.331</START_TIME>
        <STOP_TIME>1996-12-18T12:01:00.331</STOP_TIME>
      </metadata>
      <data>
        <stateVector>
          <EPOCH>1996-12-18T12:00:00.331</EPOCH>
          <X units="km">2789.619</X>
          <Y units="km">-280.045</Y>
          <Z units="km">-1746.755</Z>
          <X_DOT units="km/s">4.73372</X_DOT>
          <Y_DOT units="km/s">-2.49586</Y_DOT>
          <Z_DOT units="km/s">-1.04195</Z_DOT>
        </stateVector>
        <stateVector>
          <EPOCH>1996-12-18T12:01:00.331</EPOCH>
          <X units="km">2783.419</X>
          <Y units="km">-308.143</Y>
          <Z units="km">-1877.071</Z>
          <X_DOT units="km/s">5.18604</X_DOT>
          <Y_DOT units="km/s">-2.42124</Y_DOT>
          <Z_DOT units="km/s">-1.99608</Z_DOT>
        </stateVector>
      </data>
    </segment>
  </body>
</oem>
"""


def _full_ephemeris() -> Ephemeris:
    """A synthesised ephemeris carrying every field OEM XML requires (no ``source_native``).

    OEM XML additionally requires the header ``CREATION_DATE`` / ``ORIGINATOR`` that KVN
    treats as optional, so a "complete" XML ephemeris carries an originator and a provenance
    creation date as well as the seven mandatory META values.
    """
    return Ephemeris(
        metadata=Metadata(
            object_name="SAT",
            object_id="2024-001A",
            originator="ASTRO-TOOLS",
            central_body="EARTH",
            reference_frame="EME2000",
            time_scale="UTC",
            provenance=Provenance(source_format="synthetic", creation_date="2024-01-01T00:00:00"),
        ),
        epochs=np.array(["2024-01-01T00:00:00", "2024-01-01T00:01:00"], dtype="datetime64[ns]"),
        positions=np.array([[7000.123456, 1.0, -2.0], [6999.0, 60.5, 0.25]]),
        velocities=np.array([[0.001, 7.546, -0.5], [-0.1, 7.5, 0.0]]),
    )


# --- reader: XML -> canonical / fidelity -----------------------------------------------


def test_read_xml_returns_an_ephemeris_with_the_state_records() -> None:
    eph = read(OEM_XML_MIN)  # no format=: auto-detection routes XML content to the reader
    assert isinstance(eph, Ephemeris)
    assert len(eph) == 2
    np.testing.assert_allclose(eph.positions[0], (2789.619, -280.045, -1746.755))
    np.testing.assert_allclose(eph.velocities[0], (4.73372, -2.49586, -1.04195))
    assert eph.epochs[0] == np.datetime64("1996-12-18T12:00:00.331", "ns")
    assert eph.epochs[-1] == np.datetime64("1996-12-18T12:01:00.331", "ns")


def test_read_xml_tags_the_spine_from_the_oem_meta() -> None:
    md = read(OEM_XML_MIN).metadata
    assert md.reference_frame == "EME2000"
    assert md.central_body == "MARS BARYCENTER"
    assert md.time_scale == "UTC"
    assert md.object_name == "MARS GLOBAL SURVEYOR"
    assert md.object_id == "1996-062A"
    assert md.originator == "NASA/JPL"
    assert md.provenance is not None
    assert md.provenance.source_format == "ccsds-oem"
    assert md.provenance.creation_date == "2002-11-04T17:22:31"


def test_read_xml_records_the_serialization_on_the_fidelity_model() -> None:
    oem = read(OEM_XML_MIN).source_native
    assert isinstance(oem, OemFile)
    assert oem.serialization == "xml"
    assert oem.ccsds_version == "3.0"
    assert oem.comments == ("a test OEM",)


def test_read_xml_preserves_acceleration_and_covariance_on_the_fidelity_model() -> None:
    oem = read(GOLDEN_XML.read_bytes()).source_native
    assert isinstance(oem, OemFile)
    assert len(oem.segments) == 2
    accelerations = oem.segments[0].accelerations
    assert accelerations is not None
    np.testing.assert_allclose(accelerations[0], (0.001, 0.002, 0.003))
    covariances = oem.segments[1].covariances
    assert len(covariances) == 1
    cov = covariances[0]
    assert cov.cov_ref_frame == "RTN"
    assert len(cov.matrix) == 21
    assert cov.matrix[0] == pytest.approx(0.31)
    assert cov.matrix[-1] == pytest.approx(0.51)


def test_read_xml_preserves_comments() -> None:
    oem = read(GOLDEN_XML.read_bytes()).source_native
    assert isinstance(oem, OemFile)
    assert oem.comments == ("GEOSCIENCE LASER ALTIMETER SYSTEM",)
    assert oem.segments[0].comments == ("first arc",)


def test_multi_segment_xml_concatenates_into_one_ephemeris() -> None:
    eph = read(GOLDEN_XML.read_bytes())
    assert isinstance(eph, Ephemeris)
    assert len(eph) == 3  # 2 + 1 states across the two segments
    assert eph.epochs[-1] == np.datetime64("2003-01-13T00:02:00", "ns")
    np.testing.assert_allclose(eph.positions[-1], (6394.0, 1970.0, -1142.0))


def test_unqualified_oem_xml_round_trips_through_public_read(tmp_path: Path) -> None:
    # The committed sample carries no urn:ccsds: namespace (like our own serialiser output);
    # detection and a path-based read must still route it to the OEM reader.
    assert detect_format(SAMPLE_XML.read_bytes()) == "ccsds-oem"
    target = tmp_path / "sat.xml"
    target.write_bytes(SAMPLE_XML.read_bytes())
    eph = read(target)
    assert isinstance(eph, Ephemeris)
    assert len(eph) == 2


# --- reader: malformed XML -------------------------------------------------------------


def test_not_well_formed_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the OEM XML"):
        read(b"<oem><header>", format="ccsds-oem")


def test_xml_missing_a_required_element_is_rejected() -> None:
    broken = OEM_XML_MIN.replace(b"<ORIGINATOR>NASA/JPL</ORIGINATOR>\n", b"")
    with pytest.raises(MalformedSourceError, match="could not parse the OEM XML"):
        read(broken, format="ccsds-oem")


def test_an_oem_xml_with_no_segment_is_rejected() -> None:
    empty_body = (
        b'<?xml version="1.0" encoding="UTF-8"?>\n'
        b'<oem id="CCSDS_OEM_VERS" version="3.0">\n'
        b"  <header><CREATION_DATE>2024-01-01T00:00:00</CREATION_DATE>"
        b"<ORIGINATOR>X</ORIGINATOR></header>\n"
        b"  <body></body>\n</oem>\n"
    )
    with pytest.raises(MalformedSourceError, match="the XML body has no segment"):
        read(empty_body, format="ccsds-oem")


def test_a_partial_acceleration_triplet_is_rejected() -> None:
    broken = OEM_XML_MIN.replace(
        b'          <Z_DOT units="km/s">-1.04195</Z_DOT>\n',
        b'          <Z_DOT units="km/s">-1.04195</Z_DOT>\n'
        b'          <X_DDOT units="km/s**2">0.1</X_DDOT>\n',
    )
    with pytest.raises(MalformedSourceError, match="partial acceleration triplet"):
        read(broken, format="ccsds-oem")


def test_mixed_acceleration_xml_is_rejected() -> None:
    # The golden's first segment carries acceleration on both states; strip it from one only.
    broken = GOLDEN_XML.read_bytes().replace(
        b'          <X_DDOT units="km/s**2">0.001</X_DDOT>\n'
        b'          <Y_DDOT units="km/s**2">0.002</Y_DDOT>\n'
        b'          <Z_DDOT units="km/s**2">0.003</Z_DDOT>\n',
        b"",
        1,
    )
    with pytest.raises(MalformedSourceError, match="mixes state vectors with and without"):
        read(broken, format="ccsds-oem")


# --- writer: the three tiers in XML ----------------------------------------------------


def test_retain_source_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    eph = read(golden, retain_source=True)
    assert isinstance(eph.source_native, OemFile)
    assert eph.source_native.raw_bytes == golden
    assert write_oem(eph, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    eph = read(golden)  # no retained bytes: re-serialised structurally
    assert isinstance(eph.source_native, OemFile)
    assert eph.source_native.raw_bytes is None
    assert write_oem(eph, ".xml") == golden


def test_xml_structural_write_preserves_acceleration_and_covariance() -> None:
    eph = read(GOLDEN_XML.read_bytes())
    reread = read(write_oem(eph, ".xml"))
    before, after = eph.source_native, reread.source_native
    assert isinstance(before, OemFile) and isinstance(after, OemFile)
    acc_before = before.segments[0].accelerations
    acc_after = after.segments[0].accelerations
    assert acc_before is not None and acc_after is not None
    np.testing.assert_array_equal(acc_after, acc_before)
    assert after.segments[1].covariances[0].matrix == before.segments[1].covariances[0].matrix
    assert after.segments[1].covariances[0].cov_ref_frame == "RTN"


def test_direct_write_defaults_to_the_source_notation() -> None:
    # write_oem with no destination suffix (or one that names neither notation) re-emits in
    # whichever notation was read.
    xml_eph = read(GOLDEN_XML.read_bytes())
    kvn_eph = read(GOLDEN_KVN.read_bytes())
    assert write_oem(xml_eph).startswith(b"<?xml")
    assert write_oem(kvn_eph).startswith(b"CCSDS_OEM_VERS")
    # A neutral extension (neither .oem nor .xml) does not override the source notation.
    assert write_oem(xml_eph, ".txt").startswith(b"<?xml")


def test_destination_extension_overrides_the_source_notation() -> None:
    # An XML source written to .oem re-encodes to KVN, and a KVN source to .xml re-encodes
    # to XML — each lossless, the canonical object is unchanged on re-read.
    xml_eph = read(GOLDEN_XML.read_bytes())
    as_kvn = write_oem(xml_eph, ".oem")
    assert as_kvn.startswith(b"CCSDS_OEM_VERS")
    assert read(as_kvn) == xml_eph

    kvn_eph = read(GOLDEN_KVN.read_bytes())
    as_xml = write_oem(kvn_eph, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_eph


# --- writer: synthesised XML (the #27-style converted-object path) ----------------------


def test_synthesised_xml_write_is_valid_and_round_trips_when_complete() -> None:
    eph = _full_ephemeris()
    reread = read(write_oem(eph, ".xml"))
    assert isinstance(reread, Ephemeris)
    assert reread.metadata.object_name == "SAT"
    assert reread.metadata.reference_frame == "EME2000"
    assert reread.metadata.time_scale == "UTC"
    np.testing.assert_allclose(reread.positions, eph.positions)
    np.testing.assert_allclose(reread.velocities, eph.velocities)


def test_synthesised_xml_write_warns_for_each_missing_required_field() -> None:
    eph = Ephemeris(
        metadata=Metadata(object_name="SAT", central_body="EARTH", reference_frame="EME2000"),
        epochs=np.array(["2024-01-01T00:00:00"], dtype="datetime64[ns]"),
        positions=np.array([[7000.0, 0.0, 0.0]]),
        velocities=np.array([[0.0, 7.5, 0.0]]),
    )
    with pytest.warns(Warning) as caught:
        out = write_oem(eph, ".xml")
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    # The META OBJECT_ID / TIME_SYSTEM are absent (START/STOP come from the epochs), and OEM
    # XML additionally requires the header CREATION_DATE / ORIGINATOR.
    assert warned == {"OBJECT_ID", "TIME_SYSTEM", "CREATION_DATE", "ORIGINATOR"}
    assert out.startswith(b"<?xml")
    assert b"<OBJECT_ID>UNKNOWN</OBJECT_ID>" in out


def test_cross_notation_write_warns_when_dropping_non_standard_meta() -> None:
    # OEM XML is schema-closed, so a non-standard KVN META keyword cannot be carried across.
    kvn = b"""CCSDS_OEM_VERS = 2.0
CREATION_DATE = 2004-281T17:26:06
ORIGINATOR = ME

META_START
OBJECT_NAME = STARLETTE
OBJECT_ID = 1975-010A
CENTER_NAME = EARTH
REF_FRAME = EME2000
TIME_SYSTEM = UTC
START_TIME = 2004-100T00:00:00.000
STOP_TIME = 2004-100T00:01:00.000
USER_DEFINED_THING = keep me
META_STOP
2004-100T00:00:00.000 1.0 2.0 3.0 4.0 5.0 6.0
"""
    eph = read(kvn)
    with pytest.warns(Warning) as caught:
        out = write_oem(eph, ".xml")
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert warned == {"USER_DEFINED_THING"}
    assert out.startswith(b"<?xml")


# --- writer: the no-silent-loss contract on the XML path -------------------------------


def test_complete_synthesised_xml_write_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    eph = _full_ephemeris()
    assert_no_silent_loss(lambda: write_oem(eph, ".xml"), loses=False)


def test_xml_round_trip_of_the_golden_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    eph = read(GOLDEN_XML.read_bytes())
    assert_no_silent_loss(lambda: write_oem(eph, ".xml"), loses=False)


def test_synthesised_xml_write_with_missing_fields_warns(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    eph = Ephemeris(
        metadata=Metadata(object_name="SAT", central_body="EARTH", reference_frame="EME2000"),
        epochs=np.array(["2024-01-01T00:00:00"], dtype="datetime64[ns]"),
        positions=np.array([[7000.0, 0.0, 0.0]]),
        velocities=np.array([[0.0, 7.5, 0.0]]),
    )
    assert_no_silent_loss(lambda: write_oem(eph, ".xml"), loses=True)


# --- public write() surface ------------------------------------------------------------


def test_public_write_to_xml_extension_emits_xml(tmp_path: Path) -> None:
    eph = read(GOLDEN_KVN.read_bytes())  # a KVN source, asked to land as XML
    destination = tmp_path / "out.xml"
    write(eph, destination, format="ccsds-oem")  # .xml is too generic to infer the message
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == eph


def test_public_write_to_oem_extension_emits_kvn(tmp_path: Path) -> None:
    eph = read(GOLDEN_XML.read_bytes())  # an XML source, asked to land as KVN
    destination = tmp_path / "out.oem"
    write(eph, destination)  # .oem infers ccsds-oem and selects KVN
    assert destination.read_bytes().startswith(b"CCSDS_OEM_VERS")


def test_public_write_to_xml_is_byte_identical_with_retained_source(tmp_path: Path) -> None:
    golden = GOLDEN_XML.read_bytes()
    eph = read(golden, retain_source=True)
    destination = tmp_path / "out.xml"
    write(eph, destination, format="ccsds-oem")
    assert destination.read_bytes() == golden


def test_writing_a_bare_xml_destination_without_a_format_is_rejected(tmp_path: Path) -> None:
    # .xml names no single NDM message, so it cannot infer the format on its own.
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(_full_ephemeris(), tmp_path / "out.xml")


# --- KVN <-> XML parity (reference = KVN, candidate = XML) ------------------------------


def _assert_oemfiles_equivalent(reference: OemFile, candidate: OemFile) -> None:
    """Assert two OEM fidelity models carry identical content across the two notations.

    ``ccsds_version`` / ``serialization`` / ``raw_bytes`` are excluded by design: KVN OEM
    declares version ``2.0`` and the XML schema ``3.0`` for the same message, and the
    notation tag legitimately differs. Everything that describes the *orbit* must match.
    """
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.comments == candidate.comments
    assert len(reference.segments) == len(candidate.segments)
    for ref, cand in zip(reference.segments, candidate.segments, strict=True):
        assert ref.meta == cand.meta
        np.testing.assert_array_equal(ref.epochs, cand.epochs)
        np.testing.assert_array_equal(ref.positions, cand.positions)
        np.testing.assert_array_equal(ref.velocities, cand.velocities)
        if ref.accelerations is None:
            assert cand.accelerations is None
        else:
            assert cand.accelerations is not None
            np.testing.assert_array_equal(ref.accelerations, cand.accelerations)
        assert ref.covariances == cand.covariances
        assert ref.comments == cand.comments


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = oemfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, OemFile)
    _assert_oemfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    # Read KVN, emit XML, read it back: the canonical ephemeris is unchanged end to end.
    kvn_eph = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_oem(kvn_eph, ".xml"))
    assert via_xml == kvn_eph
