"""The CCSDS APM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`ApmFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_apm.xml`` is the XML twin of ``golden_apm.apm``
(generated by the writer from the KVN golden), so the two carry identical attitude content.
KVN is version 1.0 and XML version 2.0 — the version tokens and the v1-only ``Q_DIR`` direction
differ; everything that describes the *attitude* matches.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import numpy as np
import pytest

from orbit_formats import (
    Attitude,
    MalformedSourceError,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.apm_xml import apmfile_from_xml
from orbit_formats.readers.ccsds_apm import ApmFile
from orbit_formats.writers.apm import write_apm

DATA = Path(__file__).parent / "data" / "apm"
GOLDEN_KVN = DATA / "golden_apm.apm"
GOLDEN_XML = DATA / "golden_apm.xml"


def _assert_apmfiles_equivalent(reference: ApmFile, candidate: ApmFile) -> None:
    """Assert two APM fidelity models carry identical attitude content across the two notations.

    ``ccsds_version`` / ``serialization`` / ``raw_bytes`` are excluded by design (KVN declares
    1.0 and the XML schema 2.0), as is the version-1-only ``q_dir`` direction tag the version-2
    XML schema has no field for.
    """
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.comments == candidate.comments
    assert reference.metadata == candidate.metadata
    ref_q, cand_q = reference.quaternion, candidate.quaternion
    assert ref_q.epoch == cand_q.epoch
    assert (ref_q.q_frame_a, ref_q.q_frame_b) == (cand_q.q_frame_a, cand_q.q_frame_b)
    assert (ref_q.q1, ref_q.q2, ref_q.q3, ref_q.qc) == (cand_q.q1, cand_q.q2, cand_q.q3, cand_q.qc)
    assert (ref_q.q1_dot, ref_q.qc_dot) == (cand_q.q1_dot, cand_q.qc_dot)
    assert ref_q.comments == cand_q.comments


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_a_single_row_attitude() -> None:
    att = read(GOLDEN_XML.read_bytes())
    assert isinstance(att, Attitude)
    assert len(att) == 1
    assert att.frame_a == "EME2000"
    np.testing.assert_allclose(att.records[0], [0.195286, -0.079460, 0.318876, 0.924049])


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    att = read(GOLDEN_XML.read_bytes())
    apm = att.source_native
    assert isinstance(apm, ApmFile)
    assert apm.serialization == "xml"
    assert att.metadata.object_id == "2024-018A"


def test_unqualified_apm_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-apm"
    target = tmp_path / "att.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target, format="ccsds-apm"), Attitude)


def test_malformed_apm_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the APM XML"):
        read(b"<apm><header>", format="ccsds-apm")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    att = read(golden, retain_source=True)
    assert write_apm(att, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_apm(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_att = read(GOLDEN_XML.read_bytes())
    as_kvn = write_apm(xml_att, ".apm")
    assert as_kvn.startswith(b"CCSDS_APM_VERS")
    assert read(as_kvn) == xml_att

    kvn_att = read(GOLDEN_KVN.read_bytes())
    as_xml = write_apm(kvn_att, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_att


def test_a_quaternion_rate_survives_the_xml_round_trip() -> None:
    with_rate = read(
        GOLDEN_KVN.read_bytes().rstrip()
        + b"\nQ1_DOT = 0.001\nQ2_DOT = 0.002\nQ3_DOT = 0.003\nQC_DOT = 0.004\n"
    )
    apm = apmfile_from_xml(write_apm(with_rate, ".xml"))
    assert apm.quaternion.q1_dot == pytest.approx(0.001)
    assert apm.quaternion.qc_dot == pytest.approx(0.004)


def test_xml_write_placeholders_and_warns_for_a_missing_creation_date() -> None:
    no_header = (
        b"CCSDS_APM_VERS = 1.0\n\nMETA_START\nOBJECT_NAME = SAT\nOBJECT_ID = 2024-018A\n"
        b"TIME_SYSTEM = UTC\nMETA_STOP\n\nEPOCH = 2024-03-01T00:00:00\n"
        b"Q_FRAME_A = EME2000\nQ_FRAME_B = SC_BODY\nQ1 = 0.0\nQ2 = 0.0\nQ3 = 0.0\nQC = 1.0\n"
    )
    att = read(no_header)
    with pytest.warns(Warning) as caught:
        out = write_apm(att, ".xml")
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert {"CREATION_DATE", "ORIGINATOR"} <= warned
    assert b"UNKNOWN" in out


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    att = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(att, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(att, destination, format="ccsds-apm")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == att


def test_xml_round_trip_of_the_golden_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    att = read(GOLDEN_XML.read_bytes())
    assert_no_silent_loss(lambda: write_apm(att, ".xml"), loses=False)


def test_a_b2a_quaternion_direction_is_reported_lossy_on_an_xml_write(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    # The version-2 XML schema has no Q_DIR and assumes A2B; a B2A direction inverts the
    # rotation, so dropping it on an XML write must warn (the A2B golden does not).
    b2a = read(GOLDEN_KVN.read_bytes().replace(b"Q_DIR = A2B", b"Q_DIR = B2A"))
    assert_no_silent_loss(lambda: write_apm(b2a, ".xml"), loses=True)


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = apmfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, ApmFile)
    _assert_apmfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_att = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_apm(kvn_att, ".xml"))
    assert via_xml == kvn_att
