"""The CCSDS OCM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`OcmFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_ocm.xml`` is the XML twin of ``golden_ocm.ocm``
(generated by the writer from the KVN golden), so the two carry identical comprehensive content
— they differ only in shape (typed value / enum elements vs plain KVN keyword-value text). OCM
is version 3.0 in both notations, so there is no version skew.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from orbit_formats import (
    Ephemeris,
    MalformedSourceError,
    Metadata,
    Provenance,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.ocm_xml import ocmfile_from_xml, xml_bytes_from_ocm
from orbit_formats.readers.ccsds_ocm import OcmFile, Quantity
from orbit_formats.writers.ocm import write_ocm

DATA = Path(__file__).parent / "data" / "ocm"
GOLDEN_KVN = DATA / "golden_ocm.ocm"
GOLDEN_XML = DATA / "golden_ocm.xml"


def _assert_ocmfiles_equivalent(reference: OcmFile, candidate: OcmFile) -> None:
    """Assert two OCM fidelity models carry identical content across the two notations.

    ``serialization`` and ``raw_bytes`` are excluded by design (they record the notation, not
    the message); everything that describes the comprehensive message must match.
    """
    assert reference.ccsds_version == candidate.ccsds_version
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.message_id == candidate.message_id
    assert reference.classification == candidate.classification
    assert reference.comments == candidate.comments
    assert reference.metadata == candidate.metadata
    assert reference.trajectories == candidate.trajectories
    assert reference.physical == candidate.physical
    assert reference.covariances == candidate.covariances
    assert reference.maneuvers == candidate.maneuvers
    assert reference.perturbations == candidate.perturbations
    assert reference.orbit_determination == candidate.orbit_determination
    assert reference.user_defined == candidate.user_defined


def _full_ephemeris() -> Ephemeris:
    return Ephemeris(
        metadata=Metadata(
            object_name="SAT",
            object_id="2024-001A",
            originator="ASTRO-TOOLS",
            reference_frame="EME2000",
            central_body="EARTH",
            time_scale="UTC",
            provenance=Provenance(source_format="ccsds-ocm", creation_date="2024-01-01T00:00:00"),
        ),
        epochs=np.array(["2024-01-01T00:00:00", "2024-01-01T00:10:00"], dtype="datetime64[ns]"),
        positions=np.array([[7000.0, 0.0, 0.0], [6999.0, 60.0, 0.0]]),
        velocities=np.array([[0.0, 7.5, 0.0], [-0.1, 7.5, 0.0]]),
    )


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_an_ephemeris() -> None:
    eph = read(GOLDEN_XML.read_bytes())
    assert isinstance(eph, Ephemeris)
    assert len(eph) == 3
    assert eph.metadata.reference_frame == "EME2000"


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    eph = read(GOLDEN_XML.read_bytes())
    native = eph.source_native
    assert isinstance(native, OcmFile)
    assert native.serialization == "xml"
    assert eph.metadata.time_scale == "UTC"
    assert eph.metadata.originator == "ASTRO-TOOLS"


def test_unqualified_ocm_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-ocm"
    target = tmp_path / "orbit.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target, format="ccsds-ocm"), Ephemeris)


def test_malformed_ocm_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the OCM XML"):
        read(b"<ocm><header>", format="ccsds-ocm")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    eph = read(golden, retain_source=True)
    assert write_ocm(eph, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_ocm(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_eph = read(GOLDEN_XML.read_bytes())
    as_kvn = write_ocm(xml_eph, ".ocm")
    assert as_kvn.startswith(b"CCSDS_OCM_VERS")
    assert read(as_kvn) == xml_eph

    kvn_eph = read(GOLDEN_KVN.read_bytes())
    as_xml = write_ocm(kvn_eph, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_eph


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    eph = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(eph, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(eph, destination, format="ccsds-ocm")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == eph


def test_xml_write_placeholders_and_warns_for_missing_required_header_fields() -> None:
    native = read(GOLDEN_KVN.read_bytes()).source_native
    assert isinstance(native, OcmFile)
    stripped = replace(native, creation_date=None, originator=None)
    with pytest.warns(Warning) as caught:
        out = xml_bytes_from_ocm(stripped)
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert {"CREATION_DATE", "ORIGINATOR"} <= warned
    assert b"UNKNOWN" in out


def test_a_dimensioned_value_and_an_enum_survive_the_xml_round_trip() -> None:
    native = read(GOLDEN_KVN.read_bytes()).source_native
    assert isinstance(native, OcmFile)
    back = ocmfile_from_xml(xml_bytes_from_ocm(native))
    # WET_MASS is a value+units element, TRAJ_BASIS an enum — both must round-trip exactly.
    assert back.physical is not None
    assert back.physical.get("WET_MASS") == Quantity(1500.0, "kg")
    assert back.trajectories[0].get("TRAJ_BASIS") == "PREDICTED"


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = ocmfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, OcmFile)
    _assert_ocmfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_eph = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_ocm(kvn_eph, ".xml"))
    assert via_xml == kvn_eph


# --- no-silent-loss --------------------------------------------------------------------


def test_complete_synthesised_xml_write_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    assert_no_silent_loss(lambda: write_ocm(_full_ephemeris(), ".xml"), loses=False)


def test_xml_round_trip_of_the_golden_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    eph = read(GOLDEN_XML.read_bytes())
    assert_no_silent_loss(lambda: write_ocm(eph, ".xml"), loses=False)
