"""The sgp4-backed TLE reader: TLE/3LE -> canonical MeanElementSet, with the epoch state."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from orbit_formats import (
    MalformedSourceError,
    MeanElementSet,
    StateVector,
    detect_format,
    read,
)
from orbit_formats.readers.tle import TleCatalog, TleRecord, read_tle
from orbit_formats.registry import get_reader

_DATA = Path(__file__).parent / "data" / "tle"

# A real, checksum-valid ISS three-line element set (the canonical sgp4 test elements).
NAME_LINE = "ISS (ZARYA)"
LINE1 = "1 25544U 98067A   08264.51782528 -.00002182  00000-0 -11606-4 0  2927"
LINE2 = "2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.72125391563537"
TLE_3LE = f"{NAME_LINE}\n{LINE1}\n{LINE2}\n".encode()
TLE_2LE = f"{LINE1}\n{LINE2}\n".encode()

# SGP4 state at the element-set epoch (TEME, km and km/s), from sgp4 2.x for these elements.
EPOCH_POSITION = (4083.902463520656, -993.6319996058096, 5243.603665370765)
EPOCH_VELOCITY = (2.512837295156162, 7.259888524980963, -0.5837785365057586)
EPOCH = np.datetime64("2008-09-20T12:25:40.104192", "ns")


def _fix_checksum(body68: str) -> str:
    """Append the correct mod-10 TLE checksum to a 68-character line body."""
    total = sum(int(ch) if ch.isdigit() else 1 if ch == "-" else 0 for ch in body68)
    return body68 + str(total % 10)


def test_reader_is_registered_for_tle() -> None:
    assert get_reader("tle") is read_tle


def test_read_returns_a_mean_element_set_with_tle_native_units() -> None:
    result = read(TLE_3LE)  # no format= : exercises auto-detection routing to this reader
    assert isinstance(result, MeanElementSet)
    # Mean elements in the TLE/OMM convention: rev/day and degrees.
    assert result.mean_motion == pytest.approx(15.72125391, abs=1e-7)
    assert result.eccentricity == pytest.approx(0.0006703)
    assert result.inclination == pytest.approx(51.6416)
    assert result.raan == pytest.approx(247.4627)
    assert result.arg_periapsis == pytest.approx(130.5360)
    assert result.mean_anomaly == pytest.approx(325.0288)


def test_read_populates_the_drag_terms() -> None:
    result = read(TLE_3LE)
    assert isinstance(result, MeanElementSet)
    assert result.bstar == pytest.approx(-0.11606e-4)
    # mean_motion_dot is the TLE-printed first-derivative-over-2 term.
    assert result.mean_motion_dot == pytest.approx(-0.00002182, abs=1e-12)
    assert result.mean_motion_ddot == pytest.approx(0.0)


def test_read_tags_the_set_teme_utc_earth() -> None:
    md = read(TLE_3LE).metadata
    assert md.reference_frame == "TEME"
    assert md.central_body == "Earth"
    assert md.time_scale == "UTC"
    assert md.object_name == "ISS (ZARYA)"
    assert md.object_id == "25544"
    assert md.provenance is not None
    assert md.provenance.source_format == "tle"


def test_read_sets_the_epoch_from_the_element_set() -> None:
    result = read(TLE_3LE)
    assert isinstance(result, MeanElementSet)
    assert abs(result.epoch - EPOCH) <= np.timedelta64(1, "us")


def test_source_native_retains_the_raw_lines() -> None:
    record = read(TLE_3LE).source_native
    assert isinstance(record, TleRecord)
    assert record.line1 == LINE1
    assert record.line2 == LINE2
    assert record.name == "ISS (ZARYA)"
    assert record.format_name == "tle"


def test_epoch_state_exposes_the_single_sgp4_state() -> None:
    record = read(TLE_3LE).source_native
    assert isinstance(record, TleRecord)
    state = record.epoch_state()
    assert isinstance(state, StateVector)
    np.testing.assert_allclose(state.position, EPOCH_POSITION, atol=1e-6)
    np.testing.assert_allclose(state.velocity, EPOCH_VELOCITY, atol=1e-6)
    assert state.metadata.reference_frame == "TEME"
    assert state.metadata.time_scale == "UTC"
    assert state.metadata.object_id == "25544"
    assert abs(state.epoch - EPOCH) <= np.timedelta64(1, "us")


def test_to_dataframe_carries_the_teme_spine() -> None:
    result = read(TLE_3LE)
    assert isinstance(result, MeanElementSet)
    df = result.to_dataframe()
    assert df.attrs["coordinate_system"] == "TEME"
    assert df.attrs["time_scale"] == "UTC"
    assert len(df) == 1


def test_two_line_set_without_a_name_parses() -> None:
    result = read(TLE_2LE)
    assert isinstance(result, MeanElementSet)
    assert result.metadata.object_name is None
    assert result.metadata.object_id == "25544"


def test_three_line_name_zero_marker_is_stripped() -> None:
    tle = f"0 {NAME_LINE}\n{LINE1}\n{LINE2}\n".encode()
    assert read(tle).metadata.object_name == "ISS (ZARYA)"


def test_blank_lines_and_trailing_content_are_tolerated() -> None:
    # A leading blank line is skipped; content after the element set is ignored.
    cluttered = f"\n{NAME_LINE}\n{LINE1}\n{LINE2}\n# generated by some tool\n".encode()
    result = read(cluttered)
    assert isinstance(result, MeanElementSet)
    assert result.metadata.object_id == "25544"


def test_a_non_digit_checksum_is_rejected() -> None:
    broken = TLE_3LE.replace(b"0  2927\n", b"0  292X\n")  # non-digit in the checksum column
    with pytest.raises(MalformedSourceError, match="line 1 has an invalid checksum"):
        read(broken, format="tle")


def test_a_bad_checksum_is_rejected_with_a_clear_error() -> None:
    broken = TLE_3LE.replace(b"0  2927\n", b"0  2928\n")  # flip the line-1 checksum
    # format="tle" bypasses detection (which would itself reject the bad checksum).
    with pytest.raises(MalformedSourceError, match="line 1 has an invalid checksum"):
        read(broken, format="tle")


def test_missing_element_lines_are_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not find a complete two-line"):
        read(b"just some notes, not a TLE\n", format="tle")


def test_disagreeing_satellite_numbers_are_rejected() -> None:
    foreign_line2 = _fix_checksum("2 " + "99999" + LINE2[7:68])
    mismatched = f"{LINE1}\n{foreign_line2}\n".encode()
    with pytest.raises(MalformedSourceError, match="satellite numbers disagree"):
        read(mismatched, format="tle")


def test_the_tle_signature_is_detected_before_reading() -> None:
    # The DoD's auto-detection contract: TLE content routes to the tle format id.
    assert detect_format(TLE_3LE) == "tle"


# --- name-annotated 3LE / catalogue / alpha-5 variants ---------------------------------


def test_detection_handles_3le_catalogue_and_alpha5_files() -> None:
    # The DoD: content detection (no extension hint) routes every TLE variant to the tle id.
    for golden in ("golden_3le.3le", "golden_catalog.tle", "golden_alpha5.tle"):
        assert detect_format((_DATA / golden).read_bytes()) == "tle", golden


def test_format_3le_is_a_synonym_for_tle() -> None:
    # The 3LE is the tle format in its name-annotated notation, so format="3le" reads it.
    result = read(TLE_3LE, format="3le")
    assert isinstance(result, MeanElementSet)
    assert result.metadata.object_name == "ISS (ZARYA)"


def test_a_single_set_keeps_a_tle_record_native() -> None:
    # A lone set (2LE or 3LE) keeps the per-record fidelity model, not a catalogue.
    assert isinstance(read(TLE_3LE).source_native, TleRecord)
    assert isinstance(read(TLE_2LE).source_native, TleRecord)


def test_3le_golden_reads_with_the_object_name() -> None:
    result = read(_DATA / "golden_3le.3le")  # detection by content + the .3le extension
    assert isinstance(result, MeanElementSet)
    assert result.metadata.object_name == "ISS (ZARYA)"
    assert result.metadata.object_id == "25544"


def test_a_catalogue_parses_into_a_sequence_with_object_names() -> None:
    # The DoD: a multi-set file parses into the expected MeanElementSet sequence, names populated.
    first = read(_DATA / "golden_catalog.tle")
    catalog = first.source_native
    assert isinstance(catalog, TleCatalog)
    assert len(catalog.records) == 3
    sequence = catalog.to_canonical()
    assert [m.metadata.object_name for m in sequence] == [
        "ISS (ZARYA)",
        "NOAA 19",
        "GPS BIIR-2  (PRN 13)",
    ]
    assert [m.metadata.object_id for m in sequence] == ["25544", "33591", "24876"]
    # read() returns the first set; the canonical fields match the first sequence element.
    assert isinstance(first, MeanElementSet)
    assert first.metadata.object_name == "ISS (ZARYA)"
    assert first.mean_motion == pytest.approx(sequence[0].mean_motion)


def test_each_catalogue_record_carries_its_own_tle_record() -> None:
    catalog = read(_DATA / "golden_catalog.tle").source_native
    assert isinstance(catalog, TleCatalog)
    sequence = catalog.to_canonical()
    assert all(isinstance(m.source_native, TleRecord) for m in sequence)
    assert sequence[1].source_native is catalog.records[1]


def test_a_catalogue_record_yields_its_own_epoch_state() -> None:
    catalog = read(_DATA / "golden_catalog.tle").source_native
    assert isinstance(catalog, TleCatalog)
    state = catalog.records[2].epoch_state()
    assert isinstance(state, StateVector)
    assert state.metadata.object_id == "24876"
    assert state.metadata.reference_frame == "TEME"


def test_alpha5_designator_is_decoded() -> None:
    # The alpha-5 catalog id E8493 decodes to 148493 (E=14, then the trailing four digits).
    result = read(_DATA / "golden_alpha5.tle")
    assert isinstance(result, MeanElementSet)
    assert result.metadata.object_id == "148493"
    record = result.source_native
    assert isinstance(record, TleRecord)
    assert record.norad_catalog_number == 148493  # the property no longer trips on the letter


def test_a_line1_without_a_matching_line2_is_rejected() -> None:
    lonely = f"{NAME_LINE}\n{LINE1}\n".encode()
    with pytest.raises(MalformedSourceError, match="no matching line 2"):
        read(lonely, format="tle")
