"""The CCSDS CDM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`CdmFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_cdm.xml`` is the XML twin of ``golden_cdm.cdm``
(generated by the writer from the KVN golden), so the two carry identical conjunction content.
The CDM has a single message version (1.0) shared by both notations — the two differ only in
shape (typed value+units elements vs bracketed KVN units), so the fidelity models are equal.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from orbit_formats import (
    Conjunction,
    MalformedSourceError,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.cdm_xml import cdmfile_from_xml, xml_bytes_from_cdm
from orbit_formats.readers.ccsds_cdm import CdmFile
from orbit_formats.writers.cdm import write_cdm

DATA = Path(__file__).parent / "data" / "cdm"
GOLDEN_KVN = DATA / "golden_cdm.cdm"
GOLDEN_XML = DATA / "golden_cdm.xml"


def _assert_cdmfiles_equivalent(reference: CdmFile, candidate: CdmFile) -> None:
    """Assert two CDM fidelity models carry identical content across the two notations.

    ``serialization`` and ``raw_bytes`` are excluded by design (they record the notation, not
    the conjunction); everything that describes the conjunction must match.
    """
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.message_for == candidate.message_for
    assert reference.message_id == candidate.message_id
    assert reference.comments == candidate.comments
    assert reference.relative == candidate.relative
    assert reference.objects == candidate.objects


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_a_two_object_conjunction() -> None:
    conj = read(GOLDEN_XML.read_bytes())
    assert isinstance(conj, Conjunction)
    assert [obj.label for obj in conj.objects] == ["OBJECT1", "OBJECT2"]
    np.testing.assert_allclose(conj.objects[0].state[:3], [2570.097065, 2244.654904, 6281.497978])


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    conj = read(GOLDEN_XML.read_bytes())
    native = conj.source_native
    assert isinstance(native, CdmFile)
    assert native.serialization == "xml"
    assert conj.metadata.object_id == "12345"
    assert conj.metadata.time_scale == "UTC"


def test_unqualified_cdm_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-cdm"
    target = tmp_path / "conj.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target, format="ccsds-cdm"), Conjunction)


def test_malformed_cdm_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the CDM XML"):
        read(b"<cdm><header>", format="ccsds-cdm")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    conj = read(golden, retain_source=True)
    assert write_cdm(conj, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_cdm(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_conj = read(GOLDEN_XML.read_bytes())
    as_kvn = write_cdm(xml_conj, ".cdm")
    assert as_kvn.startswith(b"CCSDS_CDM_VERS")
    assert read(as_kvn) == xml_conj

    kvn_conj = read(GOLDEN_KVN.read_bytes())
    as_xml = write_cdm(kvn_conj, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_conj


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    conj = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(conj, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(conj, destination, format="ccsds-cdm")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == conj


def test_xml_write_placeholders_and_warns_for_missing_required_header_fields(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    # CDM XML requires the header CREATION_DATE / ORIGINATOR / MESSAGE_ID that the model treats
    # as optional; a CDM lacking them must placeholder and warn, never drop them silently.
    native = read(GOLDEN_KVN.read_bytes()).source_native
    assert isinstance(native, CdmFile)
    stripped = replace(native, creation_date=None, originator=None, message_id=None)
    with pytest.warns(Warning) as caught:
        out = xml_bytes_from_cdm(stripped)
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert {"CREATION_DATE", "ORIGINATOR", "MESSAGE_ID"} <= warned
    assert b"UNKNOWN" in out


def test_an_extended_covariance_term_survives_the_xml_round_trip() -> None:
    native = read(GOLDEN_KVN.read_bytes()).source_native
    assert isinstance(native, CdmFile)
    obj0 = native.objects[0]
    with_extended = replace(
        native,
        objects=(
            replace(obj0, covariance=replace(obj0.covariance, extended=(("CDRG_R", 0.00015),))),
            native.objects[1],
        ),
    )
    back = cdmfile_from_xml(xml_bytes_from_cdm(with_extended))
    assert back.objects[0].covariance.extended == (("CDRG_R", 0.00015),)


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = cdmfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, CdmFile)
    _assert_cdmfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_conj = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_cdm(kvn_conj, ".xml"))
    assert via_xml == kvn_conj
