"""The CCSDS TDM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`TdmFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_tdm.xml`` is the XML twin of ``golden_tdm.tdm``
(generated by the writer from the KVN golden), so the two carry identical tracking content. TDM
is version 2.0 in both notations, so the fidelity models are equal — the two differ only in
shape (typed value/enum elements vs plain KVN keyword-value text).
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import replace
from pathlib import Path

import pytest

from orbit_formats import (
    MalformedSourceError,
    Tracking,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.tdm_xml import tdmfile_from_xml, xml_bytes_from_tdm
from orbit_formats.readers.ccsds_tdm import TdmFile
from orbit_formats.writers.tdm import write_tdm

DATA = Path(__file__).parent / "data" / "tdm"
GOLDEN_KVN = DATA / "golden_tdm.tdm"
GOLDEN_XML = DATA / "golden_tdm.xml"


def _assert_tdmfiles_equivalent(reference: TdmFile, candidate: TdmFile) -> None:
    """Assert two TDM fidelity models carry identical content across the two notations.

    ``serialization`` and ``raw_bytes`` are excluded by design (they record the notation, not
    the tracking content); everything that describes the message must match.
    """
    assert reference.ccsds_version == candidate.ccsds_version
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.message_id == candidate.message_id
    assert reference.comments == candidate.comments
    assert reference.segments == candidate.segments


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_a_tracking_set() -> None:
    tracking = read(GOLDEN_XML.read_bytes())
    assert isinstance(tracking, Tracking)
    assert tracking.participants == ("DSS-25", "1999-099A")
    assert len(tracking) == 11


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    tracking = read(GOLDEN_XML.read_bytes())
    native = tracking.source_native
    assert isinstance(native, TdmFile)
    assert native.serialization == "xml"
    assert tracking.metadata.time_scale == "UTC"
    assert tracking.metadata.originator == "NASA/JPL"


def test_unqualified_tdm_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-tdm"
    target = tmp_path / "track.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target, format="ccsds-tdm"), Tracking)


def test_malformed_tdm_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the TDM XML"):
        read(b"<tdm><header>", format="ccsds-tdm")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    tracking = read(golden, retain_source=True)
    assert write_tdm(tracking, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_tdm(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_tracking = read(GOLDEN_XML.read_bytes())
    as_kvn = write_tdm(xml_tracking, ".tdm")
    assert as_kvn.startswith(b"CCSDS_TDM_VERS")
    assert read(as_kvn) == xml_tracking

    kvn_tracking = read(GOLDEN_KVN.read_bytes())
    as_xml = write_tdm(kvn_tracking, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_tracking


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    tracking = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(tracking, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(tracking, destination, format="ccsds-tdm")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == tracking


def test_xml_write_placeholders_and_warns_for_missing_required_header_fields(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    # TDM XML requires the header CREATION_DATE / ORIGINATOR that the model treats as optional;
    # a TDM lacking them must placeholder and warn, never drop them silently.
    native = read(GOLDEN_KVN.read_bytes()).source_native
    assert isinstance(native, TdmFile)
    stripped = replace(native, creation_date=None, originator=None)
    with pytest.warns(Warning) as caught:
        out = xml_bytes_from_tdm(stripped)
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert {"CREATION_DATE", "ORIGINATOR"} <= warned
    assert b"UNKNOWN" in out


def test_a_wrapped_angle_and_a_bare_float_observation_survive_the_xml_round_trip() -> None:
    native = read(GOLDEN_KVN.read_bytes()).source_native
    assert isinstance(native, TdmFile)
    back = tdmfile_from_xml(xml_bytes_from_tdm(native))
    # ANGLE_1 maps to a value+units element, RANGE to a bare float — both must round-trip.
    angle_segment = back.segments[1]
    assert angle_segment.observations[0].keyword == "ANGLE_1"
    assert angle_segment.observations[0].value == pytest.approx(12.34)
    range_segment = back.segments[0]
    ranges = [obs.value for obs in range_segment.observations if obs.keyword == "RANGE"]
    assert ranges == pytest.approx([9.0e10, 90000000123.0, 90000000246.0])


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = tdmfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, TdmFile)
    _assert_tdmfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_tracking = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_tdm(kvn_tracking, ".xml"))
    assert via_xml == kvn_tracking
