"""The CCSDS OPM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`OpmFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_opm.xml`` is the XML twin of ``golden_opm.opm``
(generated by the writer from the KVN golden), so the two carry identical orbital content.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import pytest

from orbit_formats import (
    MalformedSourceError,
    StateVector,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.opm_xml import opmfile_from_xml
from orbit_formats.readers.ccsds_opm import OpmFile
from orbit_formats.writers.opm import write_opm

DATA = Path(__file__).parent / "data" / "opm"
GOLDEN_KVN = DATA / "golden_opm.opm"
GOLDEN_XML = DATA / "golden_opm.xml"

OPM_XML_MIN = b"""<?xml version="1.0" encoding="UTF-8"?>
<opm id="CCSDS_OPM_VERS" version="3.0">
  <header>
    <CREATION_DATE>2020-065T16:00:00</CREATION_DATE>
    <ORIGINATOR>18 SPCS</ORIGINATOR>
  </header>
  <body>
    <segment>
      <metadata>
        <OBJECT_NAME>GODZILLA 5</OBJECT_NAME>
        <OBJECT_ID>1998-057A</OBJECT_ID>
        <CENTER_NAME>EARTH</CENTER_NAME>
        <REF_FRAME>EME2000</REF_FRAME>
        <TIME_SYSTEM>UTC</TIME_SYSTEM>
      </metadata>
      <data>
        <stateVector>
          <EPOCH>2020-03-04T14:28:15.1172</EPOCH>
          <X units="km">6503.514</X>
          <Y units="km">1239.647</Y>
          <Z units="km">-717.49</Z>
          <X_DOT units="km/s">-0.87316</X_DOT>
          <Y_DOT units="km/s">8.74042</Y_DOT>
          <Z_DOT units="km/s">-4.191076</Z_DOT>
        </stateVector>
      </data>
    </segment>
  </body>
</opm>
"""


def _assert_opmfiles_equivalent(reference: OpmFile, candidate: OpmFile) -> None:
    """Assert two OPM fidelity models carry identical content across the two notations.

    ``ccsds_version`` / ``serialization`` / ``raw_bytes`` are excluded by design (the two
    encodings declare different version tokens for the same content).
    """
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.message_id == candidate.message_id
    assert reference.comments == candidate.comments
    assert reference.metadata == candidate.metadata
    assert reference.state_vector == candidate.state_vector
    assert reference.keplerian == candidate.keplerian
    assert reference.spacecraft_parameters == candidate.spacecraft_parameters
    assert reference.covariance == candidate.covariance
    assert reference.maneuvers == candidate.maneuvers
    assert reference.user_defined == candidate.user_defined
    assert reference.user_defined_comments == candidate.user_defined_comments


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_a_state_vector() -> None:
    state = read(OPM_XML_MIN)
    assert isinstance(state, StateVector)
    assert state.position == pytest.approx([6503.514, 1239.647, -717.49])
    assert state.velocity == pytest.approx([-0.87316, 8.74042, -4.191076])


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    state = read(OPM_XML_MIN)
    opm = state.source_native
    assert isinstance(opm, OpmFile)
    assert opm.serialization == "xml"
    assert state.metadata.reference_frame == "EME2000"


def test_read_xml_golden_preserves_every_block() -> None:
    opm = read(GOLDEN_XML.read_bytes()).source_native
    assert isinstance(opm, OpmFile)
    assert opm.keplerian is not None and opm.keplerian.true_anomaly == pytest.approx(325.0288)
    assert opm.spacecraft_parameters is not None
    assert opm.covariance is not None and opm.covariance.cov_ref_frame == "RTN"
    assert len(opm.covariance.matrix) == 21
    assert len(opm.maneuvers) == 2
    assert opm.maneuvers[1].man_ref_frame == "RTN"
    assert opm.user_defined == (("INTLDES", "1998-057A"),)


def test_unqualified_opm_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-opm"
    target = tmp_path / "sat.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target), StateVector)


def test_malformed_opm_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the OPM XML"):
        read(b"<opm><header>", format="ccsds-opm")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    state = read(golden, retain_source=True)
    assert write_opm(state, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_opm(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_state = read(GOLDEN_XML.read_bytes())
    as_kvn = write_opm(xml_state, ".opm")
    assert as_kvn.startswith(b"CCSDS_OPM_VERS")
    assert read(as_kvn) == xml_state

    kvn_state = read(GOLDEN_KVN.read_bytes())
    as_xml = write_opm(kvn_state, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_state


def test_xml_write_placeholders_and_warns_for_a_missing_creation_date() -> None:
    # NDM/XML requires the header CREATION_DATE / ORIGINATOR that KVN treats as optional; a
    # KVN OPM without them is placeholdered on the XML write and the loss is reported.
    no_header = (
        b"CCSDS_OPM_VERS = 2.0\n"
        b"OBJECT_NAME = SAT\nOBJECT_ID = 2000-000A\nCENTER_NAME = EARTH\n"
        b"REF_FRAME = EME2000\nTIME_SYSTEM = UTC\n"
        b"EPOCH = 2024-01-01T00:00:00\nX = 7000.0\nY = 0.0\nZ = 0.0\n"
        b"X_DOT = 0.0\nY_DOT = 7.5\nZ_DOT = 0.0\n"
    )
    state = read(no_header)
    with pytest.warns(Warning) as caught:
        out = write_opm(state, ".xml")
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert {"CREATION_DATE", "ORIGINATOR"} <= warned
    assert b"UNKNOWN" in out


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    state = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(state, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(state, destination, format="ccsds-opm")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == state


def test_xml_round_trip_of_the_golden_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    state = read(GOLDEN_XML.read_bytes())
    assert_no_silent_loss(lambda: write_opm(state, ".xml"), loses=False)


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = opmfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, OpmFile)
    _assert_opmfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_state = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_opm(kvn_state, ".xml"))
    assert via_xml == kvn_state
