"""The CCSDS OMM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`OmmFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_omm.xml`` is the XML twin of ``golden_omm.omm``
(generated by the writer from the KVN golden), so the two carry identical orbital content.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import pytest

from orbit_formats import (
    MalformedSourceError,
    MeanElementSet,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.omm_xml import ommfile_from_xml
from orbit_formats.readers.ccsds_omm import OmmFile
from orbit_formats.writers.omm import write_omm

DATA = Path(__file__).parent / "data" / "omm"
GOLDEN_KVN = DATA / "golden_omm.omm"
GOLDEN_XML = DATA / "golden_omm.xml"

OMM_XML_MIN = b"""<?xml version="1.0" encoding="UTF-8"?>
<omm id="CCSDS_OMM_VERS" version="3.0">
  <header>
    <CREATION_DATE>2020-065T16:00:00</CREATION_DATE>
    <ORIGINATOR>18 SPCS</ORIGINATOR>
  </header>
  <body>
    <segment>
      <metadata>
        <OBJECT_NAME>STARLETTE</OBJECT_NAME>
        <OBJECT_ID>1975-010A</OBJECT_ID>
        <CENTER_NAME>EARTH</CENTER_NAME>
        <REF_FRAME>TEME</REF_FRAME>
        <TIME_SYSTEM>UTC</TIME_SYSTEM>
        <MEAN_ELEMENT_THEORY>SGP4</MEAN_ELEMENT_THEORY>
      </metadata>
      <data>
        <meanElements>
          <EPOCH>2020-064T10:34:41.4264</EPOCH>
          <MEAN_MOTION>13.84653757</MEAN_MOTION>
          <ECCENTRICITY>0.0205751</ECCENTRICITY>
          <INCLINATION>49.8237</INCLINATION>
          <RA_OF_ASC_NODE>99.5917</RA_OF_ASC_NODE>
          <ARG_OF_PERICENTER>224.3636</ARG_OF_PERICENTER>
          <MEAN_ANOMALY>133.6754</MEAN_ANOMALY>
        </meanElements>
        <tleParameters>
          <NORAD_CAT_ID>7646</NORAD_CAT_ID>
          <MEAN_MOTION_DOT>-0.00000016</MEAN_MOTION_DOT>
        </tleParameters>
      </data>
    </segment>
  </body>
</omm>
"""


def _assert_ommfiles_equivalent(reference: OmmFile, candidate: OmmFile) -> None:
    """Assert two OMM fidelity models carry identical content across the two notations.

    ``ccsds_version`` / ``serialization`` / ``raw_bytes`` are excluded by design (the two
    encodings declare different version tokens for the same content).
    """
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.comments == candidate.comments
    assert reference.metadata == candidate.metadata
    assert reference.mean_elements == candidate.mean_elements
    assert reference.tle_parameters == candidate.tle_parameters
    assert reference.spacecraft_parameters == candidate.spacecraft_parameters
    assert reference.covariance == candidate.covariance
    assert reference.user_defined == candidate.user_defined
    assert reference.user_defined_comments == candidate.user_defined_comments


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_a_mean_element_set() -> None:
    mean_set = read(OMM_XML_MIN)
    assert isinstance(mean_set, MeanElementSet)
    assert mean_set.mean_motion == pytest.approx(13.84653757)
    assert mean_set.inclination == pytest.approx(49.8237)
    assert mean_set.mean_motion_dot == pytest.approx(-0.00000016)


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    mean_set = read(OMM_XML_MIN)
    omm = mean_set.source_native
    assert isinstance(omm, OmmFile)
    assert omm.serialization == "xml"
    assert omm.metadata.mean_element_theory == "SGP4"
    assert mean_set.metadata.reference_frame == "TEME"


def test_read_xml_golden_preserves_every_block() -> None:
    omm = read(GOLDEN_XML.read_bytes()).source_native
    assert isinstance(omm, OmmFile)
    assert omm.spacecraft_parameters is not None
    assert omm.covariance is not None and omm.covariance.cov_ref_frame == "RTN"
    assert len(omm.covariance.matrix) == 21
    assert omm.user_defined == (("INTLDES", "1975-010A"),)


def test_unqualified_omm_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-omm"
    target = tmp_path / "sat.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target), MeanElementSet)


def test_malformed_omm_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the OMM XML"):
        read(b"<omm><header>", format="ccsds-omm")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    mean_set = read(golden, retain_source=True)
    assert write_omm(mean_set, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_omm(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_set = read(GOLDEN_XML.read_bytes())
    as_kvn = write_omm(xml_set, ".omm")
    assert as_kvn.startswith(b"CCSDS_OMM_VERS")
    assert read(as_kvn) == xml_set

    kvn_set = read(GOLDEN_KVN.read_bytes())
    as_xml = write_omm(kvn_set, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_set


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    mean_set = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(mean_set, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(mean_set, destination, format="ccsds-omm")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == mean_set


def test_xml_round_trip_of_the_golden_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    mean_set = read(GOLDEN_XML.read_bytes())
    assert_no_silent_loss(lambda: write_omm(mean_set, ".xml"), loses=False)


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = ommfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, OmmFile)
    _assert_ommfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_set = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_omm(kvn_set, ".xml"))
    assert via_xml == kvn_set
