"""The SPK (SPICE binary kernel) reader and writer behind the ``[spk]`` extra: DAF segment
parsing, the three write tiers (byte-lossless / content-lossless / synthesised), the
no-silent-loss contract, an independent SPICE cross-check, and the missing-extra error.

The committed golden (``tests/data/spk/golden.bsp``, generated by
``scripts/make_spk_golden.py``) has two segments — a type-9 (Lagrange) spacecraft segment and
a type-13 (Hermite) Moon segment, both Earth-centred in J2000 — so one file exercises both
sampled-state types and the multi-segment path. The whole module skips where ``spiceypy`` is
absent; the missing-extra test forces that absence explicitly.
"""

from __future__ import annotations

import sys
from collections.abc import Callable
from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("spiceypy")

import spiceypy as spice

from orbit_formats import (
    Ephemeris,
    MalformedSourceError,
    Metadata,
    MissingOptionalDependencyError,
    Provenance,
    StateVector,
    UnsupportedConversionError,
    convert,
    detect_format,
    read,
    write,
)
from orbit_formats._spice import J2000_TDB
from orbit_formats.readers.spk import SpkFile, read_spk
from orbit_formats.registry import get_reader, get_writer
from orbit_formats.writers.spk import write_spk

GOLDEN = Path(__file__).parent / "data" / "spk" / "golden.bsp"


def _synthesised_ephemeris() -> Ephemeris:
    """A complete ephemeris carrying every SPK-required field (no SPK source_native).

    ``MOON`` / ``EARTH`` resolve to NAIF ids, ``J2000`` is a SPICE frame, and the TDB scale
    needs no conversion — so a synthesised write of this carries nothing it must default.
    """
    return Ephemeris(
        metadata=Metadata(
            object_name="MOON",
            central_body="EARTH",
            reference_frame="J2000",
            time_scale="TDB",
            provenance=Provenance(source_format="synthetic"),
        ),
        epochs=J2000_TDB + np.arange(4).astype("timedelta64[s]") * 600,
        positions=np.array(
            [
                [384400.0, 0.0, 0.0],
                [384402.0, -10.0, 5.0],
                [384404.0, -20.0, 10.0],
                [384406.0, -30.0, 15.0],
            ]
        ),
        velocities=np.array(
            [[0.05, 1.02, -0.01], [0.05, 1.02, -0.01], [0.05, 1.02, -0.01], [0.05, 1.02, -0.01]]
        ),
    )


def _type8_kernel(path: Path) -> None:
    """Write a type-8 (equal-step Lagrange) SPK — a valid SPK whose segment type is unsupported."""
    epochs = np.array([0.0, 600.0, 1200.0, 1800.0])
    states = np.array([[7000.0, 0.0, 0.0, 0.0, 7.5, 0.0]] * 4) + np.arange(4).reshape(
        4, 1
    ) * np.array([[-1.0, 1.0, 0.0, 0.0, 0.0, 0.0]])
    handle = spice.spkopn(str(path), "type-8 probe", 0)
    try:
        spice.spkw08(
            handle, -999, 399, "J2000", epochs[0], epochs[-1], "type-8 segment",
            3, len(epochs), states.tolist(), epochs[0], 600.0,
        )  # fmt: skip
    finally:
        spice.spkcls(handle)


# --- registration & detection ----------------------------------------------------------


def test_reader_is_registered_for_spk() -> None:
    assert get_reader("spk") is read_spk


def test_writer_is_registered_for_spk() -> None:
    assert get_writer("spk") is write_spk


def test_spk_is_detected_by_binary_magic() -> None:
    assert detect_format(GOLDEN.read_bytes()) == "spk"


# --- reader ----------------------------------------------------------------------------


def test_read_returns_the_first_segment_as_an_ephemeris() -> None:
    eph = read(GOLDEN.read_bytes())  # auto-detection routes the DAF/SPK magic here
    assert isinstance(eph, Ephemeris)
    assert len(eph) == 5
    np.testing.assert_allclose(eph.positions[0], (7000.0, 0.0, 0.0))
    np.testing.assert_allclose(eph.velocities[0], (0.0, 7.5, 0.0))


def test_read_tags_the_spine_from_the_segment() -> None:
    md = read(GOLDEN.read_bytes()).metadata
    assert md.reference_frame == "J2000"
    assert md.central_body == "EARTH"
    assert md.time_scale == "TDB"  # SPK ephemeris time is TDB
    assert md.object_name == "-999"  # the spacecraft id has no SPICE name; the id is the fallback
    assert md.provenance is not None and md.provenance.source_format == "spk"


def test_read_carries_the_interpolation_hint() -> None:
    eph = read(GOLDEN.read_bytes())
    assert isinstance(eph, Ephemeris)
    assert eph.interpolation == "Lagrange"
    assert eph.interpolation_degree == 3


def test_epochs_are_tdb_seconds_past_j2000() -> None:
    eph = read(GOLDEN.read_bytes())
    assert isinstance(eph, Ephemeris)
    assert eph.epochs[0] == J2000_TDB  # the first node is at ET 0.0
    assert eph.epochs[-1] == J2000_TDB + np.timedelta64(2400, "s")


def test_source_native_holds_every_segment() -> None:
    spk = read(GOLDEN.read_bytes()).source_native
    assert isinstance(spk, SpkFile)
    assert spk.format_name == "spk"
    assert len(spk.segments) == 2
    assert [seg.segment_type for seg in spk.segments] == [9, 13]
    ephemerides = spk.segment_ephemerides()
    assert ephemerides[1].metadata.object_name == "MOON"
    assert ephemerides[1].interpolation == "Hermite"
    np.testing.assert_allclose(ephemerides[1].positions[0], (384400.0, 0.0, 0.0))


def test_read_from_a_path_matches_read_from_bytes() -> None:
    from_path = read(str(GOLDEN))
    from_bytes = read(GOLDEN.read_bytes())
    assert isinstance(from_path, Ephemeris)
    assert from_path == from_bytes


# --- reader: malformed inputs ----------------------------------------------------------


def test_a_non_daf_file_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not read the SPK file"):
        read(b"this is not a SPICE kernel\n", format="spk")


def test_an_unsupported_segment_type_is_rejected(tmp_path: Path) -> None:
    kernel = tmp_path / "type8.bsp"
    _type8_kernel(kernel)
    with pytest.raises(MalformedSourceError, match="segment type 8 is not supported"):
        read(kernel.read_bytes(), format="spk")


# --- writer: byte-lossless (opt-in) and content-lossless (default) ---------------------


def test_retain_source_round_trip_is_byte_identical() -> None:
    golden = GOLDEN.read_bytes()
    eph = read(golden, retain_source=True)
    assert isinstance(eph, Ephemeris)
    assert isinstance(eph.source_native, SpkFile)
    assert eph.source_native.raw_bytes == golden
    assert write_spk(eph) == golden


def test_default_read_retains_no_bytes() -> None:
    eph = read(GOLDEN.read_bytes())
    assert isinstance(eph.source_native, SpkFile)
    assert eph.source_native.raw_bytes is None


def test_default_round_trip_preserves_content() -> None:
    eph = read(GOLDEN.read_bytes())
    out = write_spk(eph)  # re-emits both segments via spiceypy from the fidelity model
    assert read(out) == eph  # the first-segment canonical object is unchanged


def test_round_trip_preserves_every_segment() -> None:
    eph = read(GOLDEN.read_bytes())
    reread = read(write_spk(eph))
    before = eph.source_native
    after = reread.source_native
    assert isinstance(before, SpkFile) and isinstance(after, SpkFile)
    for original, roundtripped in zip(before.segments, after.segments, strict=True):
        assert roundtripped.segment_type == original.segment_type
        np.testing.assert_allclose(roundtripped.states, original.states)
        np.testing.assert_allclose(roundtripped.epochs_et, original.epochs_et)


# The independent SPICE-evaluator cross-check (SPICE's own spkgeo reads back the states we
# wrote) lives in test_spk_oracle.py, where it runs as a standing external-cross-validation
# CI job alongside the Orekit oracle, mirroring the test_ccsds_*_oracle.py layout.


# --- writer: synthesised / cross-format ------------------------------------------------


def test_synthesised_write_is_valid_and_round_trips_when_complete() -> None:
    eph = _synthesised_ephemeris()
    reread = read(write_spk(eph))
    assert isinstance(reread, Ephemeris)
    assert reread.metadata.object_name == "MOON"
    assert reread.metadata.central_body == "EARTH"
    assert reread.metadata.reference_frame == "J2000"
    assert reread.metadata.time_scale == "TDB"
    np.testing.assert_allclose(reread.positions, eph.positions)
    np.testing.assert_allclose(reread.velocities, eph.velocities)
    np.testing.assert_array_equal(reread.epochs, eph.epochs)


def test_synthesised_write_warns_for_each_missing_required_field() -> None:
    eph = Ephemeris(
        metadata=Metadata(),  # no object_name, central_body, reference_frame, or time_scale
        epochs=J2000_TDB + np.arange(4).astype("timedelta64[s]") * 600,
        positions=np.array([[7000.0, 0.0, 0.0]] * 4) + np.arange(4).reshape(4, 1),
        velocities=np.array([[0.0, 7.5, 0.0]] * 4),
    )
    with pytest.warns(Warning) as caught:
        write_spk(eph)
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert warned == {"object_name", "central_body", "reference_frame", "time_scale"}


def test_synthesised_write_converts_a_non_tdb_time_scale() -> None:
    # A UTC ephemeris writes cleanly (UTC -> TDB is a lossless reinterpretation, no warning);
    # the re-read kernel is TDB, and the positions — untouched by a time relabel — are intact.
    eph = Ephemeris(
        metadata=Metadata(
            object_name="MOON", central_body="EARTH", reference_frame="J2000", time_scale="UTC"
        ),
        epochs=np.array(
            ["2024-01-01T00:00:00", "2024-01-01T00:10:00", "2024-01-01T00:20:00"],
            dtype="datetime64[ns]",
        ),
        positions=np.array([[384400.0, 0.0, 0.0], [384402.0, -10.0, 5.0], [384404.0, -20.0, 10.0]]),
        velocities=np.array([[0.05, 1.02, -0.01]] * 3),
    )
    reread = read(write_spk(eph))
    assert isinstance(reread, Ephemeris)
    assert reread.metadata.time_scale == "TDB"
    np.testing.assert_allclose(reread.positions, eph.positions)


def test_non_ephemeris_input_is_rejected() -> None:
    state = StateVector(
        metadata=Metadata(reference_frame="J2000"),
        epoch=np.datetime64("2024-01-01T00:00:00", "ns"),
        position=np.array([7000.0, 0.0, 0.0]),
        velocity=np.array([0.0, 7.5, 0.0]),
    )
    with pytest.raises(UnsupportedConversionError, match="spk"):
        write_spk(state)


def test_convert_to_an_ephemeris_target_is_a_same_form_passthrough() -> None:
    # spk prefers the ephemeris form, so routing an Ephemeris to it (or another ephemeris
    # target) is a no-op pass-through — the conversion-matrix cell.
    eph = read(GOLDEN.read_bytes())
    assert convert(eph, to="spk") is eph
    assert convert(eph, to="ccsds-oem") is eph


# --- the no-silent-loss contract -------------------------------------------------------


def test_same_format_write_loses_nothing(assert_no_silent_loss: Callable[..., None]) -> None:
    eph = read(GOLDEN.read_bytes())
    assert_no_silent_loss(lambda: write_spk(eph), loses=False)


def test_complete_synthesised_write_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    assert_no_silent_loss(lambda: write_spk(_synthesised_ephemeris()), loses=False)


def test_synthesised_write_with_missing_fields_warns(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    eph = Ephemeris(
        metadata=Metadata(),
        epochs=J2000_TDB + np.arange(4).astype("timedelta64[s]") * 600,
        positions=np.array([[7000.0, 0.0, 0.0]] * 4) + np.arange(4).reshape(4, 1),
        velocities=np.array([[0.0, 7.5, 0.0]] * 4),
    )
    assert_no_silent_loss(lambda: write_spk(eph), loses=True)


# --- the [spk] extra is optional -------------------------------------------------------


def test_read_without_spiceypy_raises_the_typed_install_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setitem(sys.modules, "spiceypy", None)
    with pytest.raises(MissingOptionalDependencyError, match=r"orbit-formats\[spk\]"):
        read(GOLDEN.read_bytes(), format="spk")


def test_write_without_spiceypy_raises_the_typed_install_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    eph = _synthesised_ephemeris()
    monkeypatch.setitem(sys.modules, "spiceypy", None)
    with pytest.raises(MissingOptionalDependencyError, match=r"orbit-formats\[spk\]"):
        write_spk(eph)


# --- public read / write surface -------------------------------------------------------


def test_public_write_to_file_infers_spk_from_the_extension(tmp_path: Path) -> None:
    eph = _synthesised_ephemeris()
    destination = tmp_path / "out.bsp"
    write(eph, destination)
    assert destination.read_bytes()[:8] == b"DAF/SPK "
    assert read(destination) == read(write_spk(eph))


def test_public_write_byte_identical_with_retained_source(tmp_path: Path) -> None:
    golden = GOLDEN.read_bytes()
    eph = read(golden, retain_source=True)
    destination = tmp_path / "echo.bsp"
    write(eph, destination)
    assert destination.read_bytes() == golden
