"""The CCSDS AEM XML reader and writer, and KVN ↔ XML parity.

The XML path parses into the *same* :class:`AemFile` the KVN reader produces and serialises
back out through the xsdata bindings. ``golden_aem.xml`` is the XML twin of ``golden_aem.aem``
(generated by the writer from the KVN golden), so the two carry identical attitude content.
KVN is version 1.0 and XML version 2.0, so the version tokens and the v1-only ``ATTITUDE_DIR``
/ ``QUATERNION_TYPE`` notation tags differ; everything that describes the *attitude* matches.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import numpy as np
import pytest

from orbit_formats import (
    Attitude,
    MalformedSourceError,
    UnknownFormatError,
    detect_format,
    read,
    write,
)
from orbit_formats.adapters.aem_xml import aemfile_from_xml
from orbit_formats.readers.ccsds_aem import AemFile
from orbit_formats.writers.aem import write_aem

DATA = Path(__file__).parent / "data" / "aem"
GOLDEN_KVN = DATA / "golden_aem.aem"
GOLDEN_XML = DATA / "golden_aem.xml"


def _assert_aemfiles_equivalent(reference: AemFile, candidate: AemFile) -> None:
    """Assert two AEM fidelity models carry identical attitude content across the two notations.

    ``ccsds_version`` / ``serialization`` / ``raw_bytes`` are excluded by design (KVN declares
    1.0 and the XML schema 2.0 for the same message), as are the version-1-only ``attitude_dir``
    and ``quaternion_type`` notation tags the version-2 XML schema has no field for.
    """
    assert reference.creation_date == candidate.creation_date
    assert reference.originator == candidate.originator
    assert reference.comments == candidate.comments
    assert len(reference.segments) == len(candidate.segments)
    for ref, cand in zip(reference.segments, candidate.segments, strict=True):
        assert ref.meta.object_name == cand.meta.object_name
        assert ref.meta.object_id == cand.meta.object_id
        assert ref.meta.center_name == cand.meta.center_name
        assert (ref.meta.ref_frame_a, ref.meta.ref_frame_b) == (
            cand.meta.ref_frame_a,
            cand.meta.ref_frame_b,
        )
        assert ref.meta.time_system == cand.meta.time_system
        assert (ref.meta.start_time, ref.meta.stop_time) == (
            cand.meta.start_time,
            cand.meta.stop_time,
        )
        assert ref.meta.attitude_type == cand.meta.attitude_type
        assert ref.meta.euler_rot_seq == cand.meta.euler_rot_seq
        assert ref.meta.interpolation_method == cand.meta.interpolation_method
        assert ref.meta.interpolation_degree == cand.meta.interpolation_degree
        assert ref.meta.comments == cand.meta.comments
        np.testing.assert_array_equal(ref.epochs, cand.epochs)
        np.testing.assert_array_equal(ref.records, cand.records)
        assert ref.comments == cand.comments


# --- reader ----------------------------------------------------------------------------


def test_read_xml_returns_an_attitude() -> None:
    att = read(GOLDEN_XML.read_bytes())
    assert isinstance(att, Attitude)
    assert att.attitude_type == "QUATERNION"
    assert att.frame_a == "EME2000"
    np.testing.assert_allclose(att.records[0], [0.195286, -0.079460, 0.318876, 0.924049])


def test_read_xml_records_serialization_and_tags_the_spine() -> None:
    att = read(GOLDEN_XML.read_bytes())
    aem = att.source_native
    assert isinstance(aem, AemFile)
    assert aem.serialization == "xml"
    assert att.metadata.object_id == "2024-018A"


def test_unqualified_aem_xml_is_detected_and_read_from_path(tmp_path: Path) -> None:
    assert detect_format(GOLDEN_XML.read_bytes()) == "ccsds-aem"
    target = tmp_path / "att.xml"
    target.write_bytes(GOLDEN_XML.read_bytes())
    assert isinstance(read(target, format="ccsds-aem"), Attitude)


def test_malformed_aem_xml_is_rejected() -> None:
    with pytest.raises(MalformedSourceError, match="could not parse the AEM XML"):
        read(b"<aem><header>", format="ccsds-aem")


# --- writer tiers ----------------------------------------------------------------------


def test_retain_source_xml_round_trip_is_byte_identical() -> None:
    golden = GOLDEN_XML.read_bytes()
    att = read(golden, retain_source=True)
    assert write_aem(att, ".xml") == golden


def test_default_xml_round_trip_is_byte_stable_against_the_golden() -> None:
    golden = GOLDEN_XML.read_bytes()
    assert write_aem(read(golden), ".xml") == golden


def test_destination_extension_overrides_the_source_notation() -> None:
    xml_att = read(GOLDEN_XML.read_bytes())
    as_kvn = write_aem(xml_att, ".aem")
    assert as_kvn.startswith(b"CCSDS_AEM_VERS")
    assert read(as_kvn) == xml_att

    kvn_att = read(GOLDEN_KVN.read_bytes())
    as_xml = write_aem(kvn_att, ".xml")
    assert as_xml.startswith(b"<?xml")
    assert read(as_xml) == kvn_att


def test_euler_rotation_sequence_maps_to_the_xml_axis_form() -> None:
    euler = read(
        b"CCSDS_AEM_VERS = 1.0\nCREATION_DATE = 2024-03-01T12:00:00\nORIGINATOR = OF\n\n"
        b"META_START\nOBJECT_NAME = SAT\nOBJECT_ID = 2024-018A\nREF_FRAME_A = EME2000\n"
        b"REF_FRAME_B = SC_BODY\nTIME_SYSTEM = UTC\nSTART_TIME = 2024-03-01T00:00:00\n"
        b"STOP_TIME = 2024-03-01T00:00:00\nATTITUDE_TYPE = EULER_ANGLE\nEULER_ROT_SEQ = 321\n"
        b"META_STOP\n\nDATA_START\n2024-03-01T00:00:00 35.45 -15.75 18.80\nDATA_STOP\n"
    )
    out = write_aem(euler, ".xml")
    assert b"<EULER_ROT_SEQ>ZYX</EULER_ROT_SEQ>" in out
    assert read(out) == euler


def test_xml_write_placeholders_and_warns_for_a_missing_creation_date() -> None:
    no_header = (
        b"CCSDS_AEM_VERS = 1.0\n\nMETA_START\nOBJECT_NAME = SAT\nOBJECT_ID = 2024-018A\n"
        b"REF_FRAME_A = EME2000\nREF_FRAME_B = SC_BODY\nTIME_SYSTEM = UTC\n"
        b"START_TIME = 2024-03-01T00:00:00\nSTOP_TIME = 2024-03-01T00:00:00\n"
        b"ATTITUDE_TYPE = QUATERNION\nMETA_STOP\n\nDATA_START\n"
        b"2024-03-01T00:00:00 0.0 0.0 0.0 1.0\nDATA_STOP\n"
    )
    att = read(no_header)
    with pytest.warns(Warning) as caught:
        out = write_aem(att, ".xml")
    warned = {field for record in caught for field in getattr(record.message, "fields", ())}
    assert {"CREATION_DATE", "ORIGINATOR"} <= warned
    assert b"UNKNOWN" in out


def test_public_write_to_xml_needs_an_explicit_format(tmp_path: Path) -> None:
    att = read(GOLDEN_KVN.read_bytes())
    with pytest.raises(UnknownFormatError, match="could not infer the target format"):
        write(att, tmp_path / "out.xml")
    destination = tmp_path / "out.xml"
    write(att, destination, format="ccsds-aem")
    assert destination.read_bytes().startswith(b"<?xml")
    assert read(destination) == att


def test_xml_round_trip_of_the_golden_loses_nothing(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    att = read(GOLDEN_XML.read_bytes())
    assert_no_silent_loss(lambda: write_aem(att, ".xml"), loses=False)


def test_a_b2a_attitude_direction_is_reported_lossy_on_an_xml_write(
    assert_no_silent_loss: Callable[..., None],
) -> None:
    # The version-2 XML schema has no ATTITUDE_DIR and assumes A2B; a B2A direction inverts
    # the rotation, so dropping it on an XML write must warn (the A2B golden does not).
    b2a = read(GOLDEN_KVN.read_bytes().replace(b"ATTITUDE_DIR = A2B", b"ATTITUDE_DIR = B2A"))
    assert_no_silent_loss(lambda: write_aem(b2a, ".xml"), loses=True)


# --- KVN <-> XML parity ----------------------------------------------------------------


def test_kvn_and_xml_parse_to_equivalent_models() -> None:
    reference = read(GOLDEN_KVN.read_bytes()).source_native
    candidate = aemfile_from_xml(GOLDEN_XML.read_bytes())
    assert isinstance(reference, AemFile)
    _assert_aemfiles_equivalent(reference, candidate)


def test_parity_holds_through_a_kvn_to_xml_to_kvn_round_trip() -> None:
    kvn_att = read(GOLDEN_KVN.read_bytes())
    via_xml = read(write_aem(kvn_att, ".xml"))
    assert via_xml == kvn_att
